#!/bin/bash
echo "Fixing files code style with PSR1 and PSR2 rules"
echo "================================="

echo "Fixing Harpia folder"
bin/php-cs-fixer fix Harpia --rules=@PSR1,-@PSR2

echo "Fixing app folder"
bin/php-cs-fixer fix app --rules=@PSR1,-@PSR2

echo "Fixing modulos folder"
bin/php-cs-fixer fix modulos --rules=@PSR1,-@PSR2

echo "Fixing database folder"
bin/php-cs-fixer fix database --rules=@PSR1,-@PSR2

echo "Fixing config folder"
bin/php-cs-fixer fix config --rules=@PSR1,-@PSR2

echo "Fixing tests folder"
bin/php-cs-fixer fix tests --rules=@PSR1,-@PSR2