FORMAT: 1A
HOST: http://localhost/moodle

# Integração

Plugin de integração entre Matraca e o Moodle

# Group Integracao

Usado para testar a conectividade com o plugin

## Ping [/integracao_ping]

### Verificar conectividade [GET]
+ Request (application/json)
	+ Attributes (PingRequest)

+ Response 200 (application/json)
	+ Attributes (PingResponse)

+ Response 400 (application/json)
	+ Attributes (PingError)


# Data Structures

## PingRequest (object)
+ wstoken: "suqyg122ashgsas65sdsee6" (string) - O token do plugin

## PingResponse (object)
+ response: "1" (number) - 1 se o token é valido

## PingError (object)
+ response: "1" (number) - 0 se o token é valido